theme: add doom-bluloco-dark and doom-bluloco-light themes
doomemacs/themes pull request #764
Opened 2022-11-22 17:57 UTC by RazikSF

Both dark and light themes are ported from VS Code's Bluloco themes.

<img width="1411" alt="screenshot-doom-blulobo-dark" src="https://user-images.githubusercontent.com/10257736/203386307-7b9b1f76-0575-4535-b56f-bbc1538435ad.png">

<img width="1408" alt="screenshot-doom-blulobo-light" src="https://user-images.githubusercontent.com/10257736/203386344-605d6ba8-9f82-45f4-abb3-2e7b413a8094.png">

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [x] My changes are visual; I've included before and after screenshots.

2023-05-28 05:41 UTC, hankertrix commented
Would love for this to be merged into the repository!

2023-08-31 21:11 UTC, gagbo requested changes
Seems good, there are a just a bunch of formatting changes in the markdown that slipped in

2023-08-31 21:11 UTC, gagbo commented on README.md
> +support, but will work fine anywhere else.
Is it possible to revert the formatting changes?

2023-08-31 21:11 UTC, gagbo commented on README.md
> +
Is it possible to revert the formatting changes?

2023-08-31 21:11 UTC, gagbo commented on README.md
> +  - [Planned themes](#planned-themes)
Is it possible to revert the formatting changes?

2023-08-31 21:11 UTC, gagbo commented on README.md
> +```emacs-lisp
Is it possible to revert the formatting changes?

2023-08-31 21:11 UTC, gagbo commented on README.md
>  ## Theme list
Is it possible to revert the formatting changes?

2023-08-31 21:11 UTC, gagbo commented on README.md
> +| --------------------------------- | -------------------------------------------------------------------------------------- | ------------------------------------------------------------------------
Is it possible to revert the formatting changes?

2023-08-31 21:11 UTC, gagbo commented on README.md
> +| doom-pine                         | [link](https://github.com/morhetz/gruvbox)                                             | a green-tinged Gruvbox (by [@RomanHargrave](https://github.com/RomanHarg
Is it possible to revert the formatting changes?

2023-08-31 21:11 UTC, gagbo commented on README.md
> +
Is it possible to revert the formatting changes?

2023-08-31 21:11 UTC, gagbo commented on README.md
> +
Is it possible to revert the formatting changes?

2023-08-31 21:11 UTC, gagbo commented on README.md
> +
Is it possible to revert the formatting changes?

2023-08-31 21:11 UTC, gagbo commented on README.md
>  [emacs.d]: https://github.com/hlissner/.emacs.d
Is it possible to revert the formatting changes?

2023-08-31 21:11 UTC, gagbo commented on README.md
>  [snazzy]: https://github.com/sindresorhus/hyper-snazzy
Is it possible to revert the formatting changes?

2023-08-31 21:11 UTC, gagbo commented on README.md
> +[fosterhangdaan]: https://github.com/FosterHangdaan
Is it possible to revert the formatting changes?

2023-09-02 10:41 UTC, RazikSF commented
> Seems good, there are a just a bunch of formatting changes in the markdown that slipped in

Thanks for the reviews. I reverted the markdown to its initial formatting.

2023-09-06 15:31 UTC, hlissner approved these changes

2023-09-07 16:37 UTC, hlissner requested changes
Would you mind squashing both 11d3bdd7b62214fff0e941c10cb0cf4a1cd986c9 and 2f8ba5816811f4d27366b3d2aa744d73737c3428 into c15ec12fb7abc9a6c15b64645f345dc303a2a417? Otherwise, this PR looks great! I look forward to merging it.

2023-09-07 20:03 UTC, RazikSF commented
> Would you mind squashing both [11d3bdd](https://github.com/doomemacs/themes/commit/11d3bdd7b62214fff0e941c10cb0cf4a1cd986c9) and [2f8ba58](https://github.com/doomemacs/themes/commit/2f8ba5816811f4d27366b3d2aa744d73737c3428) into [c15ec12](https://github.com/doomemacs/themes/commit/c15ec12fb7abc9a6c15b64645f345dc303a2a417)? Otherwise, this PR looks great! I look forward to merging it.

Thank you! Done! I hope it worked.

2023-09-07 20:04 UTC, hlissner approved these changes

2023-09-08 21:24 UTC, merged

2023-09-08 21:25 UTC, hlissner commented
LGTM! Thanks for your help!

2023-11-16 22:45 UTC, uloco commented
@RazikSF Just wanted to say thank you for porting bluloco 🙏🏼 There is a neovim version too, so if you need any more inspiration you can have a look https://github.com/uloco/bluloco.nvim

2023-11-19 11:02 UTC, RazikSF commented
> @RazikSF Just wanted to say thank you for porting bluloco 🙏🏼 There is a neovim version too, so if you need any more inspiration you can have a look https://github.com/uloco/bluloco.nvim

Thank you for your amazing theme @uloco! I will definitely take a look for more inspiration.